Temp plotting fix
nanograv/timing_analysis pull request #8
Opened 2022-11-29 22:31 UTC by tcromartie

For be/rx combos without markers or colors in the plotting dict, assigns a black 'x' and throws a warning to avoid crashing.

2022-11-29 22:45 UTC, swiggumj requested changes
I think something may have gone wrong with pulling latest updates since lots of functions are being removed as a part of this PR. If that's also getting fixed and it's not too much trouble, it might also be good to fix bare exceptions.

2022-11-29 22:55 UTC, tcromartie commented
Oh it's a conflict with my plotting PR, I made a mistake.

2022-11-30 15:16 UTC, JPGlaser commented on src/timing_analysis/plot_utils.py
> +    if 'fmt' in kwargs.keys():
It looks like possible indentation changes between the old file and the new. Is that intended?

~ Joe G.

2022-11-30 18:40 UTC, swiggumj approved these changes
My previous concerns have been addressed, but it would be good to resolve a couple comments from Joe G. before merging.

2022-11-30 18:44 UTC, merged